version: "3.9"

services:
  chat-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DBNAME}
    ports:
      - 5437:5432
  chat-redis:
    image: redis
    restart: always
    ports:
      - 6379:6379